# nginx-app.yaml
apiVersion: apps/v1
kind: Deployment
meta
  name: nginx-test
  namespace: default
  labels:
    app: nginx-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-test
  template:
    meta
      labels:
        app: nginx-test
    spec:
      containers:
      - name: nginx
        image: nginx:stable-alpine
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
meta
  name: nginx-test-service
  namespace: default
spec:
  selector:
    app: nginx-test
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
meta
  name: nginx-test-config
  namespace: default
data:
  message: "Hello from GitOps!"
  version: "1.0.0"
